name: PR Environment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/setup-kubectl@v3

      - name: Set kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Create Namespace for PR
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          NS="ephermal-ns-$PR_ID"
          kubectl create namespace $NS --dry-run=client -o yaml | kubectl apply -f -
          echo "Namespace created: $NS"
##